import Head from "next/head";
import Layout from "../components/layout";
import { useState, useEffect } from "react";
import { IAssetsResponse, IAssetType } from "../models/asset-type";
import Table from "../components/table";
import AccordionComponent from "../components/accordion";
import { Box } from "@mui/material";
import AssetsForm from "../components/assets-form";
import {
  fetchAssets,
  createdAsset,
  deleteAsset,
  searchAssetsByName,
} from "../asset-service";
import TextInput from "../components/inputs/text-input";
import SearcuInput from "../components/inputs/search-input";
import { useGridCsvExport } from "@mui/x-data-grid/internals";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [assets, setAssets] = useState<IAssetsResponse[]>([]);
  const [search, setSearch] = useState("");

  const handleGetAssests = () => {
    setIsLoading(true);
    fetchAssets()
      .then((data) => {
        if (data) {
          setAssets(data);
        }
      })
      .finally(() => setIsLoading(false));
  };

  const handelAddAssets = (value: IAssetType) => {
    setIsLoading(true);
    createdAsset(value)
      .then(() => {
        handleGetAssests();
      })
      .finally(() => setIsLoading(false));
  };

  const handelDeleteAssets = (id: string) => {
    setIsLoading(true);
    deleteAsset(id)
      .then(() => {
        handleGetAssests();
      })
      .finally(() => setIsLoading(false));
  };

  const handleSearch = () => {
    setIsLoading(true);
    searchAssetsByName(search)
      .then((data) => {
        if (data) {
          setAssets(data);
        }
      })
      .finally(() => setIsLoading(false));
  };

  useEffect(() => {
    handleGetAssests();
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => {
      handleSearch();
    }, 800);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search]);

  return (
    <>
      <Head>
        <title>Diligent Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layout>
        <Box>
          <AccordionComponent title="Add asset">
            <AssetsForm handelAddAssets={handelAddAssets} />
          </AccordionComponent>
        </Box>
        <Box>
          <SearcuInput
            handleChange={setSearch}
            value={search}
            placeholder="Search table"
          />
        </Box>
        <Table
          data={assets}
          isLoading={isLoading}
          handelDeleteAssets={handelDeleteAssets}
        />
      </Layout>
    </>
  );
}
