import Head from "next/head";
import Layout from "../components/layout";
import { useState } from "react";
import { AssetType } from "../models/project-type";
import { Status } from "../models/status-enum";
import Table from "../components/table";
import AccordionComponent from "../components/accordion";
import { Box } from "@mui/material";
import AssetsForm from "../components/assets-form";

const data = [
  {
    name: "Confluence",
    description: "Manage software development assets",
    quantity: 1,
    status: Status.Pending,
    id: "123412412",
  },
  {
    name: "Github",
    description: "Code hosting platform",
    quantity: 3,
    status: Status.Online,
    id: "123412wgs2",
  },
  {
    name: "Jira",
    description: "Create issues",
    quantity: 1,
    status: Status.Online,
    id: "12341sdg12",
  },
];

export default function Home() {
  const [assets, setAssets] = useState<AssetType[]>(data);

  const handelAdd = (value: AssetType) => {
    setAssets([...assets, value]);
  };

  return (
    <>
      <Head>
        <title>Diligent Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layout>
        <Box>
          <AccordionComponent title="Add asset">
            <AssetsForm handelAdd={handelAdd} />
          </AccordionComponent>
        </Box>
        <Table data={assets} />
      </Layout>
    </>
  );
}
